version: '3.9'
services:
    postgres:
      image: postgres:latest
      restart: always
      ports:
        - 4000:5432
      hostname: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: abc@123
        POSTGRESS_DB: urlshortner
      volumes:
        - .UrlDbdata:/var/lib/postgresql/data